name: Build CRA application
on: [push]
jobs:
  deploy:
    name: Build pack and send to telegram
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Build pack
        env:
          REACT_APP_WEATHER_API_KEY: 123123123123
        run: npm run build
      - name: Create archive
        run: |
          sudo apt-get install zip
          zip package-${{ steps.date.outputs.date }}.zip build/
      - name: Send to telegram
        uses: BronyDust/send-deployment-status-to-telegram@master
        if: ${{ always() }}
        with:
          attach: package-${{ steps.date.outputs.date }}.zip
          service-header: 🌑 New **Development Chrome Extension** package
          deployment-to: live
          bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat-id: ${{ secrets.TELEGRAM_CHAT_ID }}
          status: ${{ job.status }}d
